# Generated by Django 4.0.5 on 2022-06-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belongings',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='belongings',
            name='type_belonging',
            field=models.CharField(choices=[('furniture', 'Furniture'), ('kitchenware', 'Kitchenware'), ('clothes', 'Clothes'), ('toys', 'Toys'), ('electronics', 'Electronics')], max_length=20),
        ),
    ]
