# Generated by Django 4.0.5 on 2022-06-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_belongings_quantity_alter_belongings_type_belonging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movingtruck',
            name='quantity',
        ),
    ]
